CREATE TABLE IF NOT EXISTS `Accounts` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `account_number` VARCHAR(12) NOT NULL,
  `user_id` INT NOT NULL,
  `balance` DECIMAL(18, 2) NOT NULL DEFAULT('0'),
  `account_type` VARCHAR(50) NOT NULL,
  `created` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `modified` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  UNIQUE (`account_number`)
)