CREATE TABLE IF NOT EXISTS `SystemProperties` (
    `id` INT NOT NULL AUTO_INCREMENT,
    `property` VARCHAR(20) NOT NULL,
    `type` VARCHAR(20) NOT NULL,
    `value` DECIMAL(18, 2) NOT NULL DEFAULT('0'),
    `created` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    `modified` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    PRIMARY KEY (`id`),
    UNIQUE (`type`)
)